# Lab 02: Manipulate PyTorch Tensors -- exercise

In [1]:
import torch

### Make the matrices A and B below. Add them together to obtain a matrix C. Print these three matrices.
$$
A =\begin{bmatrix}
1 & 2 \\ 3 & 4
\end{bmatrix}  
\qquad 
B =\begin{bmatrix}
10 & 20 \\ 30 & 40
\end{bmatrix}  \qquad C=A+B =?
$$

In [2]:

# write your code here
A = torch.Tensor([[1,2],[3,4]])
B = torch.Tensor([[10,20],[30,40]])
C = A + B

print(f"A = \n {A}")
print(f"B = \n {B}")
print(f"C = \n {C}")

A = 
 tensor([[1., 2.],
        [3., 4.]])
B = 
 tensor([[10., 20.],
        [30., 40.]])
C = 
 tensor([[11., 22.],
        [33., 44.]])


### Print the dimension, size and type of the matrix A. Remember, the commands are dim(), size() and type()

In [3]:

# write your code here
print(f"A.dim() = {A.dim()}")
print(f"A.size() = {A.size()}")
print(f"A.type() = {A.type()}")


A.dim() = 2
A.size() = torch.Size([2, 2])
A.type() = torch.FloatTensor


### Convert the matrix A to be an integer matrix  (type LongTensor). Remember, the command is long(). Then print the type to check it was indeed converted.

In [12]:
A = A.long()
print(f"A.long() = \n {A}")

A.long() = 
 tensor([[1, 2],
        [3, 4]])


### Make a random 5 x 2 x 3 Tensor. The command is torch.rand.  Then do the following:   1) Print the tensor,  2) Print its type, 3) Print its dimension,  4) Print its size, 5) Print the size of its middle dimension.

In [14]:

# write your code here
A = torch.rand(5,2,3)
print(f"A = \n {A}")
print(f"A.dim() = {A.dim()}")
print(f"A.size() = {A.size()}")
print(f"A.type() = {A.type()}")

A = 
 tensor([[[0.0903, 0.6273, 0.9577],
         [0.7602, 0.9850, 0.6532]],

        [[0.0418, 0.7229, 0.7469],
         [0.2984, 0.6038, 0.8201]],

        [[0.9545, 0.4702, 0.1261],
         [0.7985, 0.1942, 0.8598]],

        [[0.3500, 0.2591, 0.8583],
         [0.2065, 0.1257, 0.2141]],

        [[0.6040, 0.9815, 0.9226],
         [0.3721, 0.5357, 0.2746]]])
A.dim() = 3
A.size() = torch.Size([5, 2, 3])
A.type() = torch.FloatTensor


### Make 2 x 3 x 4 x 5 tensor filled with zeros then print it. (The command is torch.zeros). See if you can make sense of the display.

In [15]:

# write your code here

A = torch.zeros(2,3,4,5)
print(f"A = \n {A}")

A = 
 tensor([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]])
