# Vanilla NN & MLP

# 1.  Linear Layer

In [17]:
import torch
import torch.nn as nn

input_dimension = 5
output_dimension = 3

""" initialize a linear layer = initialize weights(hyperparameters) for the linear layer
"""
linear_layer = nn.Linear(input_dimension,output_dimension)

print(linear_layer.weight)
print(linear_layer.bias)

""" modify the weight and bias in linear layer 
"""
with torch.no_grad():
    linear_layer.weight[0,0]=0
    linear_layer.weight[0,1]=1
    linear_layer.weight[0,2]=2
    print(linear_layer.weight.data)

# OR (coding test1 qns 8)

# Initialize the weight matrices
linear_layer.weight.data.fill_(1.0)
# Initialize the biases
linear_layer.bias.data.fill_(0.5)


print(linear_layer.weight)
print(linear_layer.bias)


""" Compute linear layer 
"""
x = torch.rand(input_dimension)
y = linear_layer(x)

print(x.size(), y.size())


Parameter containing:
tensor([[ 0.3950, -0.1735,  0.0810, -0.1386,  0.4441],
        [-0.1807,  0.3634,  0.2658,  0.4104, -0.3758],
        [ 0.3731,  0.0005,  0.1566,  0.0676, -0.0070]], requires_grad=True)
Parameter containing:
tensor([-0.3481,  0.0419,  0.4329], requires_grad=True)
tensor([[ 0.0000e+00,  1.0000e+00,  2.0000e+00, -1.3864e-01,  4.4415e-01],
        [-1.8068e-01,  3.6335e-01,  2.6575e-01,  4.1041e-01, -3.7578e-01],
        [ 3.7312e-01,  5.4437e-04,  1.5662e-01,  6.7616e-02, -7.0125e-03]])
Parameter containing:
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], requires_grad=True)
Parameter containing:
tensor([0.5000, 0.5000, 0.5000], requires_grad=True)
torch.Size([5]) torch.Size([3])


# 2. Softmax

In [34]:
""" quiz 3
"""
input_dimension = 2
output_dimension = 3
""" initialize a linear layer = initialize weights(hyperparameters) for the linear layer
"""
linear_layer = nn.Linear(input_dimension,output_dimension, bias=False)

print(linear_layer.weight)
linear_layer.weight.data = torch.Tensor([[1,1],
                                        [2,0],
                                        [1,0]])
print(linear_layer.weight)


# with torch.no_grad():
#     linear_layer.weight.data = torch.nn.Parameter([ [1,1],
#                             [2,0],
#                             [1,0]])
#     print(linear_layer.weight.data)
x = torch.Tensor([2,1])
A = linear_layer(x)

torch.softmax(A , dim=0)

Parameter containing:
tensor([[-0.6786, -0.1916],
        [-0.2442,  0.2401],
        [-0.5029, -0.4463]], requires_grad=True)
Parameter containing:
tensor([[1., 1.],
        [2., 0.],
        [1., 0.]], requires_grad=True)


tensor([0.2447, 0.6652, 0.0900], grad_fn=<SoftmaxBackward>)

# MLP dimension